### ISSUE TITLE
Implementar seções do site

### ISSUE THREAD

**Issue by igorsantos07** [PHPRio/phprio.github.io#6]
# Apoio
- [x] página de texto descrevendo benefícios à empresa e comunidade
- [x] ~com um (google?) form de contato~ substituído ao sugerir contato pelo Telegram

# Vagas
- [x] Página falando sobre como divulgamos as vagas, e onde os interessados podem encontrá-las (linkar para as redes sociais onde divulgamos - Telegram, Lista?)
- [x] Google Form para envio de novas vagas

# Eventos (movidos para #17)
- [x] Página descrevendo os formatos de eventos que temos (Boteco, Meetup, Mão na Massa, edições passadas do PHP'n Rio)
- [x] Link do Meetup
- [x] ~Calendário (ainda vamos usar? Melhor sugerir integrar com a conta do Meetup)~
- [x] ~link do Call4Paperz do evento~ _isso pode ser divulgado direto no post relativo ao evento_
- [x] ~Arquivo de fotos~

## Palestras [#9]
- [x] Página explicando que as palestras são voluntárias, e como as pessoas podem se inscrever (aka acompanhar as notícias e se inscrever no C4P)
- [x] Cada uma das palestras que já tivemos, com os dados do palestrante, link da apresentação, local, etc etc

# Quem Somos
- [x] Texto sobre nossa organização horizontal #20 
- [x] ~Fotos de acontecimentos históricos~ movido pro #17 também
- [x] O que é PHP? Link para o PHP.net
- [x] Membros (mais ativos? talvez listar só os que tiveram alguma participação? sei lá...) (maior detalhamento movido para a #18)

# Participe
- [x] Criado na home, aproveitando a estrutura de bloquinhos do template, e mantendo bem à vista todos os nossos canais

-----------------

![image](https://cloud.githubusercontent.com/assets/532299/21412030/19d6d3ee-c7d4-11e6-9a64-b0493520c252.png)

**Comment by augustojoselg** [comment]
Página falando sobre como divulgamos as vagas, e onde os interessados podem encontrá-las (linkar para as redes sociais onde divulgamos - Telegram, Lista?)

**Comment by igorsantos07** [comment]
:arrow_up: foi adicionado na lista do ticket, e fechado no 765b486

**Comment by igorsantos07** [comment]
Todos os pontos daqui ou foram finalizados ou foram movidos para issues menores.
